#!/bin/bash

sourceDir=$(dirname $(readlink -f $0))

if[ -x ~/.bashrc ];then rm ~/.bashrc; fi
if[ -x ~/.bash_profile ];then rm ~/.bash_profile; fi
if[ -x ~/.bash_logout ];then rm ~/.bash_logout; fi
cp ${sourceDir}/.bashrc ~/.bashrc
cp ${sourceDir}/.bash_profile ~/.bash_profile
cp ${sourceDir}/.bash_logout ~/.bash_logout
