#!/bin/bash

sourceDir=$(dirname $(readlink -f $0))

rm ~/.bashrc && cp ${sourceDir}/.bashrc ~/.bashrc
rm ~/.bash_profile && cp ${sourceDir}/.bash_profile ~/.bash_profile
rm ~/.bash_logout && cp ${sourceDir}/.bash_logout ~/.bash_logout
