#!/bin/bash

# Identify OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     OS=Linux;;
    Darwin*)    OS=Mac;;
    CYGWIN*)    OS=Cygwin;;
    MINGW*)     OS=MinGw;;
    *)          OS="UNKNOWN:${unameOut}"
esac

if [[ "$OS" != "Mac" ]]; then
  sourceDir=$(dirname $(readlink -f $0))
else
  sourceDir=$(dirname $(greadlink -f $0))
fi

if [ -x ~/.bashrc ]; then
  rm ~/.bashrc
fi
if [ -x ~/.bash_profile ]; then
  rm ~/.bash_profile
fi
if [ -x ~/.bash_logout ]; then
  rm ~/.bash_logout
fi

cp ${sourceDir}/.bashrc ~/.bashrc
cp ${sourceDir}/.bash_profile ~/.bash_profile
cp ${sourceDir}/.bash_logout ~/.bash_logout
